# Generated by Django 3.2.5 on 2023-06-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_busstop_squashed_0018_alter_busshift_has_enough_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busshift',
            name='has_enough_stops',
        ),
    ]
