# Generated by Django 3.2.5 on 2023-07-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_busshift_total_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busshift',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='busshift',
            name='start_datetime',
        ),
    ]
